name: Deploy

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 12.x ]
        java-version: [ 11 ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/setup-java@v2.3.1
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install --frozen-lockfile # will run `yarn install` command
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: global add node-w3c-validator
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build # will run `yarn build` command
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: checkvalidate # will run `yarn test` command
      # Deploy
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "lab-5-site-design" #Must be unique in Heroku
          heroku_email: ${{secrets.EMAIL}}
